### PR TITLE
27readiness

### PR DESCRIPTION
**Pull request by jpeak5**
removes forumng query; updates other queries to use logstore table.

Unable to test:
- hotpot
- scorm
- assignment (2 ?)

### CODE REVIEW

**Comment by rrusso** [comment]
No clue about this. Apparently it wasn't merged for a reason as your current changes are different.

**Comment by jpeak5** [comment]
who knows; it's working now, we believe

**Comment by rrusso** [comment]
It is working now. Verified!!!

**Comment by jpeak5** [comment]
Won't!

---- Robert Russo wrote ----

It is working now. Verified!!!

##

**Comment by rrusso** [comment]
Won't???

**Comment by jpeak5** [comment]
woot! damn you auto-correct

**Pull request closed without merging**
